In [1]:
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier

digits = datasets.load_digits()

x = digits.images.reshape((digits.images.shape[0], digits.images.shape[1]*digits.images.shape[2]))
y = digits.target

x_train = x[:1000]
print(x_train)
y_train = y[:1000]
print(y_train)
x_test = x[1000:]
y_test = y[1000:]

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  3. ...  9.  0.  0.]
 [ 0.  0.  0. ...  6.  0.  0.]
 [ 0.  0.  9. ... 10.  0.  0.]]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0
 9 8 9 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9
 5 2 8 2 0 0 1 7 6 3 2 1 7 4 6 3 1 3 9 1 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4
 4 7 2 8 2 2 5 7 9 5 4 8 8 4 9 0 8 9 8 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7
 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0 9 8 9 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2
 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9 5 2 8 2 0 0 1 7 6 3 2 1 7 3 1 3 9 1
 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4 4 7 2 8 2 2 5 5 4 8 8 4 9 0 8 9 8 0 1 2
 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0 9 8 9
 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9 5 2 8
 2 0 0 1 7 6 3 2 1 7 4 6 3 1 3 9 1 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4 4 7 2
 8 2 2 5 7 9 5 4 8 8 4 9 0 8 9 3 0 1 2 3 4 5 6 7 8 9 0 1 2

In [2]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(15,), 
                    activation='logistic', 
                    solver='sgd', 
                    tol=1e-4, 
                    learning_rate_init=.1, 
                    verbose=False)

mlp.fit(x_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(15,), learning_rate='constant',
       learning_rate_init=0.1, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [3]:
predictions = mlp.predict(x_test)

In [4]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

array([[76,  0,  0,  0,  0,  1,  2,  0,  0,  0],
       [ 0, 68,  0,  2,  1,  1,  2,  1,  0,  5],
       [ 0,  0, 71,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0, 61,  0,  4,  0,  3,  6,  2],
       [ 0,  2,  0,  0, 79,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  0, 79,  2,  1,  0,  0],
       [ 0,  3,  0,  0,  0,  0, 77,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 78,  0,  1],
       [ 0,  1,  0,  0,  0,  3,  0,  1, 69,  2],
       [ 0,  0,  0,  2,  0,  5,  0,  2,  0, 72]], dtype=int64)

In [5]:
import pandas as pd

pd.crosstab(y_test, predictions, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted   0   1   2   3   4   5   6   7   8   9  All
True                                                  
0          76   0   0   0   0   1   2   0   0   0   79
1           0  68   0   2   1   1   2   1   0   5   80
2           0   0  71   6   0   0   0   0   0   0   77
3           0   3   0  61   0   4   0   3   6   2   79
4           0   2   0   0  79   0   0   0   0   2   83
5           0   0   0   0   0  79   2   1   0   0   82
6           0   3   0   0   0   0  77   0   0   0   80
7           0   0   0   0   1   0   0  78   0   1   80
8           0   1   0   0   0   3   0   1  69   2   76
9           0   0   0   2   0   5   0   2   0  72   81
All        76  77  71  71  81  93  83  86  75  84  797

In [8]:
print(mlp.coefs_[1])

[[ 1.47645126 -1.14845734  2.69376654 -2.43549934 -0.77381641 -1.45100171
  -1.23673829  0.54737008 -1.00394227  2.36875974]
 [ 1.11674895 -1.07127129  0.97089929  0.71483186 -2.06003715 -0.97531651
   1.46350085 -1.84936472  1.51796157 -0.13599792]
 [-2.47281257  1.33500783 -0.18554143  0.90204765 -1.98729358  1.52509504
   0.73142244 -2.86147111  0.46559725  1.24111981]
 [ 1.47829035 -1.38673835 -2.22046416  0.94567036  0.66219378  2.54124988
  -1.98913961  1.33732412 -2.81352344  2.16986425]
 [-1.23705713 -0.37107439 -1.41359711 -1.02252929  1.67686282  2.40131498
   2.14395211  1.57422146 -1.92571937 -1.5611696 ]
 [ 0.41378556  0.58590996 -0.18278694  0.50272504  0.33521327 -1.82342208
   0.45652606  0.15755334  0.94798464 -1.63581807]
 [-1.45024496  1.0493617   0.98598586 -3.61740096  0.75357102  1.18178986
   0.89147952  0.60389225  1.66762703 -1.75538474]
 [ 0.72772404 -4.16040331  1.09113303  1.27522036 -2.29122137  1.75874415
  -1.26914374  1.82831937  1.45090362 -0.13207988]


In [9]:
print(mlp.intercepts_[0])
print(mlp.intercepts_[1])

[-0.13580773  0.14150879  0.11666142 -0.05189418  0.04206077  0.06796264
 -0.08121294  0.01580895  0.03178832  0.14781081  0.15502194  0.06116698
 -0.01610282  0.05068915 -0.04868156]
[ 0.00922617  0.07426879 -0.5234518   0.14989177  0.21272444 -0.46718737
  0.15516371 -0.2754087   0.01874851 -0.37321704]


In [11]:
import pandas as pd

data = pd.read_csv('digits.csv', header=None)
data

0   1   2   3   4   5   6   7   8   9   ...  55  56  57  58  59  60  61  \
0      0   0   5  13   9   1   0   0   0   0  ...   0   0   0   6  13  10   0   
1      0   0   0  12  13   5   0   0   0   0  ...   0   0   0   0  11  16  10   
2      0   0   0   4  15  12   0   0   0   0  ...   0   0   0   0   3  11  16   
3      0   0   7  15  13   1   0   0   0   8  ...   0   0   0   7  13  13   9   
4      0   0   0   1  11   0   0   0   0   0  ...   0   0   0   0   2  16   4   
5      0   0  12  10   0   0   0   0   0   0  ...   0   0   0   9  16  16  10   
6      0   0   0  12  13   0   0   0   0   0  ...   0   0   0   1   9  15  11   
7      0   0   7   8  13  16  15   1   0   0  ...   0   0   0  13   5   0   0   
8      0   0   9  14   8   1   0   0   0   0  ...   0   0   0  11  16  15  11   
9      0   0  11  12   0   0   0   0   0   2  ...   0   0   0   9  12  13   3   
10     0   0   1   9  15  11   0   0   0   0  ...   0   0   0   1  10  13   3   
11     0   0   0   0  14  13   1   0   0   0  ...   0   0   0   0   1  13  16   
12     0   0   5  12   1   0   0   0   0   0  ...   2   0   0   3  11   8  13   
13     0   2   9  15  14   9   3   0   0   4  ...   0   0   2  12  12  13  11   
14     0   0   0   8  15   1   0   0   0   0  ...   0   0   0   0  10  15   4   
15     0   5  12  13  16  16   2   0   0  11  ...   0   0   4  15  16   2   0   
16     0   0   0   8  15   1   0   0   0   0  ...   2   0   0   0   7  15  16   
17     0   0   1   8  15  10   0   0   0   3  ...   0   0   0   0  11   9   0   
18     0   0  10   7  13   9   0   0   0   0  ...   0   0   0  11  14   5   0   
19     0   0   6  14   4   0   0   0   0   0  ...   2   0   0   7  16  16  13   
20     0   0   3  13  11   7   0   0   0   0  ...   0   0   0   2  12  13   4   
21     0   0   0   2  16  16   2   0   0   0  ...   0   0   0   0   2  12  15   
22     0   0   8  16   5   0   0   0   0   1  ...   0   0   0   7  12  12  12   
23     0   1   8  12  15  14   4   0   0   3  ...   0   0   0  14  15  11   2   
24     0   0   0   0  12   2   0   0   0   0  ...   0   0   0   0   0  12   8   
25     0   0  12   8   8   7   0   0   0   3  ...   0   0   0  11  14   9   0   
26     0   0   1  13  14   3   0   0   0   0  ...   0   0   0   3  12  15  14   
27     0   0   0   8  14  14   2   0   0   0  ...   0   0   0   0  12  13   1   
28     0   0  10  11   4   0   0   0   0   0  ...   0   0   0   8  14   7   1   
29     0   0   9  13   7   0   0   0   0   0  ...   2   0   0   7  12  12  12   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
1767   0   0   0   2  16   1   0   0   0   0  ...   0   0   0   0   3  16   7   
1768   0   0   5  16  10   0   0   0   0   0  ...   0   0   0   4  15  16   8   
1769   0   0   9  12  14   6   0   0   0   0  ...   0   0   0  12  14   9   2   
1770   0   2  10  12  16   8   0   0   0   4  ...   0   0   2  14  16  12   9   
1771   0   0   0   6  12   6   0   0   0   0  ...   0   0   0   0   6  11  12   
1772   0   0   5  14  11   8   0   0   0   4  ...   0   0   0   7  15  12   5   
1773   0   0   2  13  10   0   0   0   0   0  ...   0   0   0   1  12  16  14   
1774   0   0   6  12  12   6   0   0   0   0  ...   0   0   0   2  11  10   4   
1775   0   0   6  16  16   3   0   0   0   0  ...   0   0   0  11  11   0   0   
1776   0   0  12  16  16   7   0   0   0   3  ...   0   0   0  10  12  12   4   
1777   0   0   0   2  14   0   0   0   0   0  ...   0   0   0   0   1  13   3   
1778   0   0   0   1  13   8   0   0   0   0  ...   0   0   0   0   0  15   7   
1779   0   0   3  10  16  16   4   0   0   0  ...   0   0   0   3  12   0   0   
1780   0   3  14  15   6   0   0   0   0   7  ...   0   0   4  15  13  12  11   
1781   0   0  10  16  14   5   0   0   0   2  ...   0   0   1  11  16  15   6   
1782   0   1  10  13   2   0   0   0   0  10  ...   0   0   0   9  13  11  10   
1783   0   0  15  13   1   0   0   0   0   0  ...   0   0   0  10  13  10   6   
1784   0   0   1  10  14  13   1   0 

In [14]:


x.train = np.array(data.iloc[0:1000, 0:64])
y.train = np.array(data.iloc[0:1000, 64:65]).reshape(1000)
x.test = np.array(data.iloc[0:1000, 0:64])
y.test = np.array(data.iloc[0:1000, 64:65]).reshape(1000)


AttributeError: 'numpy.ndarray' object has no attribute 'train'

In [29]:
import pandas as pd

data = pd.read_csv('simpsons.csv')
# for i in range(0,9):
#     if data.gender[i] == "M":
#         data.gender[i] = 0
#     elif data.gender[i] == "F":
#         data.gender[i] = 1
data['gender'] = data['gender'].map({'M':0, 'F':1})

data = data.drop('Unnamed: 0', axis=1)
x = data.drop('gender', axis=1)
y = data['gender']

print(x)
print(y)

   hair_length  weight  age
0            0     250   36
1           10     150   34
2            2      90   10
3            6      78    8
4            4      20    1
5            1     170   70
6            8     160   41
7           10     180   38
8            6     200   45
0    0
1    1
2    0
3    1
4    1
5    0
6    1
7    0
8    0
Name: gender, dtype: int64


In [30]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier(criterion = 'entropy', max_depth = 3)
dtc.fit(x,y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [31]:
from sklearn.tree import export_graphviz
export_graphviz(dtc,
               out_file = 'decision_tree.dot',
               feature_names = x.columns,
               class_names = ['M', 'F'],
               rounded = True)